### ISSUE TITLE
Fix issues with SRA download

### ISSUE THREAD

**Issue by JRWallace** [compbiocore/bioflows#51]
```
Traceback (most recent call last):
  File "/gpfs/runtime/cbc_conda/cbc_conda_v1_root/envs/cbc_conda_v1/bin/bioflows-run", line 11, in <module>
    load_entry_point('bioflows==0.99', 'console_scripts', 'bioflows-run')()
  File "/gpfs/runtime/cbc_conda/cbc_conda_v1_root/envs/cbc_conda_v1/lib/python2.7/site-packages/bioflows/definedworkflows/rnaseq/rnaseqworkflow.py", line 1214, in gatk_main
    gt1 = GatkFlow(parmsfile)
  File "/gpfs/runtime/cbc_conda/cbc_conda_v1_root/envs/cbc_conda_v1/lib/python2.7/site-packages/bioflows/definedworkflows/rnaseq/rnaseqworkflow.py", line 1081, in __init__
    self.init(parmsfile)
  File "/gpfs/runtime/cbc_conda/cbc_conda_v1_root/envs/cbc_conda_v1/lib/python2.7/site-packages/bioflows/definedworkflows/rnaseq/rnaseqworkflow.py", line 293, in __init__
    self.parse_sample_info_from_sra()
  File "/gpfs/runtime/cbc_conda/cbc_conda_v1_root/envs/cbc_conda_v1/lib/python2.7/site-packages/bioflows/definedworkflows/rnaseq/rnaseqworkflow.py", line 427, in parse_sample_info_from_sra
    sample_sra = SraUtils(self.sra_info)
  File "/gpfs/runtime/cbc_conda/cbc_conda_v1_root/envs/cbc_conda_v1/lib/python2.7/site-packages/bioflows/bioutils/access_sra/sra.py", line 50, in __init__
    self.get_sra_records()
  File "/gpfs/runtime/cbc_conda/cbc_conda_v1_root/envs/cbc_conda_v1/lib/python2.7/site-packages/bioflows/bioutils/access_sra/sra.py", line 125, in get_sra_records
    self.sample_to_file[key_name] = [self.ftp_url(key_name)]
  File "/gpfs/runtime/cbc_conda/cbc_conda_v1_root/envs/cbc_conda_v1/lib/python2.7/site-packages/bioflows/bioutils/access_sra/sra.py", line 68, in ftp_url
    sra_path =  sp.check_output( "source /gpfs/runtime/cbc_conda/bin/activate_cbc_conda && srapath " + id , shell = True)
  File "/gpfs/runtime/cbc_conda/cbc_conda_v1_root/envs/cbc_conda_v1/lib/python2.7/subprocess.py", line 223, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command 'source /gpfs/runtime/cbc_conda/bin/activate_cbc_conda && srapath SRS2506568_SRX3176873' returned non-zero exit status 3
```

**Comment by JRWallace** [comment]
Fixed the issue, which was an issue with SRA paths.
