### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by kir0ul** [compbiocore/bioflows#68]
Hi,

I get an `IndexError` when I try to reproduce the [RNA-Seq tutorial](https://compbiocore.github.io/bioflows/tutorials/rna-seq_tutorial/):
```
(cbc_conda_v1) [apierre3@gpu2001 rnaseq_tutorial]$ bioflows-run test_run.yaml
Traceback (most recent call last):
  File "/gpfs/runtime/cbc_conda/cbc_conda_v1_root/envs/cbc_conda_v1/bin/bioflows-run", line 11, in <module>
    load_entry_point('bioflows==0.99', 'console_scripts', 'bioflows-run')()
  File "/gpfs/runtime/cbc_conda/cbc_conda_v1_root/envs/cbc_conda_v1/lib/python2.7/site-packages/bioflows/definedworkflows/rnaseq/rnaseqworkflow.py", line 1217, in gatk_main
    gt1 = GatkFlow(parmsfile)
  File "/gpfs/runtime/cbc_conda/cbc_conda_v1_root/envs/cbc_conda_v1/lib/python2.7/site-packages/bioflows/definedworkflows/rnaseq/rnaseqworkflow.py", line 1084, in __init__
    self.init(parmsfile)
  File "/gpfs/runtime/cbc_conda/cbc_conda_v1_root/envs/cbc_conda_v1/lib/python2.7/site-packages/bioflows/definedworkflows/rnaseq/rnaseqworkflow.py", line 291, in __init__
    self.parse_sample_info_from_file()
  File "/gpfs/runtime/cbc_conda/cbc_conda_v1_root/envs/cbc_conda_v1/lib/python2.7/site-packages/bioflows/definedworkflows/rnaseq/rnaseqworkflow.py", line 414, in parse_sample_info_from_file
    self.sample_fastq[tmpline[0]].append(tmpline[1])
IndexError: list index out of range
```

This is my manifest file:
```
(cbc_conda_v1) [apierre3@login003 rnaseq_tutorial]$ cat sample_manifest_min.csv 
samp_1299,/gpfs/data/cbc/rnaseq_test_data/PE_hg/Cb2_1.gz,/gpfs/data/cbc/rnaseq_test_data/PE_hg/Cb2_2.gz
samp_1214,/gpfs/data/cbc/rnaseq_test_data/PE_hg/Cb_1.gz,/gpfs/data/cbc/rnaseq_test_data/PE_hg/Cb_2.gz
```
And I changed the following lines in the `test_run.yaml` file:
```yaml
run_parms:
  conda_command: source /gpfs/runtime/cbc_conda/bin/activate_cbc_conda
  work_dir: /users/apierre3/scratch/rnaseq_tutorial
  log_dir: logs
  paired_end: True
  local_targets: False
  saga_host: localhost
  ssh_user: apierre3
```

Any idea what's going on?

**Comment by JRWallace** [comment]
Can you show me the full contents of your `test_run.yaml` file?

**Comment by kir0ul** [comment]
Thanks! :pray:
That seems to work now!
